# Obter a lista de colaborador
GET http://localhost:3000/api/colaboradores
Content-Type: application/json
###


# Inserir novo colaborador
POST http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "nome": "Jaqson Dalboscoo", "email": "jaqson98@upf.br",
 "celular": "99999-99", "senha": "123"

}
###

# Excluir um colaboradores
DELETE http://localhost:3000/api/colaboradores/623e4e6f62cfbd17dad03d95
Content-Type: application/json
###

# Alterar usuário
PUT http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "_id": "623e3fcea6f633ad5bb09823",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com",
 "celular": "99999-99"

}
###

# Obter pelo id de colaboradores 
GET http://localhost:3000/api/colaboradores/623e4025d5039cdb59a2d156
Content-Type: application/json
###

# Obter usuários colaboradores
GET http://localhost:3000/api/colaboradores/filtro/jaqson
Content-Type: application/json
###

